#+TITLE: Virtual machine. Interpret byte-code.
#+AUTHOR: Anas Rchid

* Abstract

#+BEGIN_QUOTE
The /VM/ reads a byte-code generated by the compiler. It has a well defined structure that's built upon operations (OPs) and their parameters. The /VM/ serve as an arena in which /champions/ are loaded into a shared memory resource. In which the players /execute/ operation for the purpose dis-functioning other players.

Thenceforth, the last player that was declared /alive/ wins as the game terminates when all players are dead.
#+END_QUOTE

* Memory

We have 4KB of memory, and each player is loaded into a page in the memory where all pages are separated equivalently. All operations address a memory address relative to a page --- /module page size/. Except of long operations (=lfork=, =lld=, =lldi=), these address the absolute memory range.

* The /fetch-decode-execute/ Cycle

after reading the header, all what's left is the instructions that we would execute. instructions are operations with parameters.
