/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   compile.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: archid- <archid-@student.1337.ma>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/02/19 15:25:02 by archid-           #+#    #+#             */
/*   Updated: 2021/02/24 17:59:25 by archid-          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "parser.h"
#include "write.h"
#include "op_impl.h"

static int i = 0;

static void		dump_line(void *blob)
{
	ft_printf(" line %d `%s`\n", i++, blob);
}

void			dump_file(void)
{
	int i = 0;
	while (i < CHAMP_MAX_SIZE)
	{
		ft_printf("%02x ", g_champ.file[i++]);
		if (i%32 == 0)
			ft_putendl("");
	}
}

t_st			compile(t_lst lines, const char *outname)
{
	t_lst			ops;
	t_st			st;
	int				fd;

	lst_iter(lines, true, dump_line);
	if ((fd = open(outname, O_CREAT | O_TRUNC | O_WRONLY, 0777)) < 0)
	{
		ft_dprintf(2, "cannot open file descriptor for writing %s!\n", outname);
		return (st_error);
	}
	else if ((ops = parse_ops(lines)))
	{
		if ((st = write_prog(ops)) == st_succ)
		{
			if (write(fd, g_champ.file, g_champ.prog_size) < g_champ.prog_size)
				ft_dprintf(2, "cannot write %s\n", outname);
			else
				ft_dprintf(2, "wrote %s\n", outname);
		}
		lst_del(&ops);
		close(fd);
		return st;
	}
	else
	{
		ft_dprintf(2, "couldn't parse operations\n");
		close(fd);
		return st_error;
	}
}

static void		substitute_label(void *blob, void *argu)
{
	t_op			*op;
	t_arg			arg;

	if (*(t_st *)argu != st_succ)
		return ;
	arg = 0;
	op = blob;
	while (arg < op->info.nargs)
	{
		if (op->labels[arg])
		{
			if (hash_get(g_labels, op->labels[arg], NULL))
				write_arg(&op->info, arg, op->addr + arg_offset(&op->info, arg));
			else
			{
				ft_dprintf(2, "referencing unknown label %s\n", op->labels[arg]);
				*(t_st *)argu = st_error;
				break;
			}
		}
		arg++;
	}
}

t_st			write_prog(t_lst ops)
{
	t_s16			size;
	t_st			st;

	size = 0;
	lst_iter_arg(ops, true, &size, write_op);
	if (size == -1)
	{
		ft_dprintf(2, "The generated byte-code exceeds the program size limit %d\n",
				   CHAMP_MAX_SIZE);
		return st_error;
	}
	g_champ.prog_size = size;
	st = st_succ;
	lst_iter_arg(ops, true, &st, substitute_label);
	return (st);
}
