/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   compile.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: archid- <archid-@student.1337.ma>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/02/19 15:25:02 by archid-           #+#    #+#             */
/*   Updated: 2021/02/24 17:59:25 by archid-          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "parser.h"
#include "op_impl.h"

static int i = 0;

static void		dump_line(void *blob)
{
	ft_printf(" line %d `%s`\n", i++, blob);
}

void			dump_file(void)
{
	int i = 0;
	while (i < CHAMP_MAX_SIZE)
	{
		ft_printf("%02x ", g_champ.file[i++]);
		if (i%32 == 0)
			ft_putendl("");
	}
}

t_st			compile(t_lst lines, const char *outname)
{
	t_lst			ops;
	t_st			st;
	int				fd;

	lst_iter(lines, true, dump_line);
	if ((fd = open(outname, O_CREAT | O_TRUNC | O_WRONLY, 0777)) < 0)
	{
		ft_dprintf(2, "cannot open file descriptor for writing %s!\n", outname);
		return (st_error);
	}
	else if ((ops = parse_ops(lines)))
	{
		st = write_prog(ops);
		lst_del(&ops);
		/* write(fd, ) */
		close(fd);
		return st;
	}
	else
	{
		ft_dprintf(2, "couldn't parse operations\n");
		close(fd);
		return st_error;
	}
}

static t_u8		arg_offset(const t_op_info *info, t_arg arg)
{
	t_arg			type;

	if ((type = encoded(op_encoding(info, arg++))) == T_REG)
		return 1;
	else if (type == T_DIR)
		return info->meta.of.short_chunk ? IND_SIZE : REG_SIZE;
	else
		return IND_SIZE;

}

static t_u8		op_memory_footprint(const t_op *op)
{
	t_u8			size;
	t_arg			arg;

	size = 1;
	if (op->info.meta.of.encoded)
		size += 1;
	arg = 0;
	while (arg < op->info.nargs)
		size += arg_offset(&op->info, arg++);
	return (size);
}

static t_s16		write_arg(const t_op_info *info, const t_arg arg, t_s16 at)
{
	t_arg			type;

	if ((type = encoded(op_encoding(info, arg))) == T_REG)
		g_champ.file[at++] = info->args.v[arg];
	else if (type == T_DIR && !info->meta.of.short_chunk)
	{
		g_champ.file[at++] = info->args.c[arg].val.byte_1;
		g_champ.file[at++] = info->args.c[arg].val.byte_2;
		g_champ.file[at++] = info->args.c[arg].val.byte_3;
		g_champ.file[at++] = info->args.c[arg].val.byte_4;
	}
	else
	{
		g_champ.file[at++] = info->args.c[arg].val.byte_1;
		g_champ.file[at++] = info->args.c[arg].val.byte_2;
	}
	return (at);
}

static void		write_args(const t_op *op, t_s16 *size)
{
	t_arg			arg;

	arg = 0;
	while (arg < op->info.nargs)
		*size += write_arg(&op->info, arg++, *size);
}

static void		write_op(void *blob, void *size)
{
	t_op			*op;
	t_s16			at;

	if (!(op = blob) || (at = *(t_s16 *)size) < 0)
		return ;
	else if ((at + op_memory_footprint(op)) < CHAMP_MAX_SIZE)
	{
		op->addr = *(t_s16 *)size;
		g_champ.file[at++] = op->info.code;
		if (op->info.meta.of.encoded)
			g_champ.file[at++] = op->info.encoded.encod;
		write_args(op, &at);
		*(t_s16 *)size = at;
	}
	else
		*(t_s16 *)size = -1;
}

static void		substitute_label(void *blob, void *argu)
{
	t_op			*op;
	t_arg			arg;

	if (*(t_st *)argu != st_succ)
		return ;
	arg = 0;
	op = blob;
	while (arg < op->info.nargs)
	{
		if (op->labels[arg])
		{
			if (hash_get(g_labels, op->labels[arg], NULL))
				write_arg(&op->info, arg, op->addr + arg_offset(&op->info, arg));
			else
			{
				ft_dprintf(2, "referencing unknown label %s\n", op->labels[arg]);
				*(t_st *)argu = st_error;
				break;
			}
		}
		arg++;
	}
}

t_st			write_prog(t_lst ops)
{
	t_s16			size;
	t_st			st;

	size = 0;
	lst_iter_arg(ops, true, &size, write_op);
	if (size == -1)
	{
		ft_dprintf(2, "The generated byte-code exceeds the program size limit %d\n",
				   CHAMP_MAX_SIZE);
		return st_error;
	}
	st = st_succ;
	lst_iter_arg(ops, true, &st, substitute_label);
	return (st);
}
