name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: distcheck
      run: make distcheck
    - name: make
      run: make
    - name: test
      run: |
          sudo apt-get install valgrind -y
          make test
